spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/java_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: example
      initial-size: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
      min-idle: 1

mybatis:
  type-aliases-package: im.qxw.stringbootbybatis.entity
  mapper-locations: classpath:mapper/*.xml
