spring:
  datasource:
    druid:
      url: jdbc:mysql://HOST/DATABASE?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username:
      password:
      initial-size: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver